# Site settings
title: BevisYu's Blog
email: ywnbit@163.com
description: > # this means to ignore newlines until "baseurl:"
    Yesterday you said tomorrow.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  ywnbit
encoding: utf-8

paginate: 8
paginate_path: "post/page:num"

# Build settings
markdown: kramdown
highlighter: pygments
